-- ============================================================
-- Deal Reports Table
-- Stores weekly Israeli tech deal reports generated by the CCR agent
-- ============================================================

CREATE TABLE IF NOT EXISTS deal_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  report_date DATE NOT NULL UNIQUE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE deal_reports ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read deal reports
CREATE POLICY "deal_reports_read_policy" ON deal_reports
  FOR SELECT
  TO authenticated
  USING (true);

-- Admins and associates can manually upload reports (mirrors companies create permission)
-- GitHub Actions uses service_role key which bypasses RLS entirely
CREATE POLICY "deal_reports_insert_policy" ON deal_reports
  FOR INSERT
  TO authenticated
  WITH CHECK (can_perform_action('companies', 'create'));

CREATE POLICY "deal_reports_update_policy" ON deal_reports
  FOR UPDATE
  TO authenticated
  USING (can_perform_action('companies', 'update'))
  WITH CHECK (can_perform_action('companies', 'update'));

-- Index for efficient date-based queries (newest first)
CREATE INDEX IF NOT EXISTS idx_deal_reports_date ON deal_reports(report_date DESC);

COMMENT ON TABLE deal_reports IS 'Weekly Israeli tech deal reports generated by the Menomadin CCR agent';
COMMENT ON COLUMN deal_reports.report_date IS 'Report date matching the filename YYYY-MM-DD.md';
COMMENT ON COLUMN deal_reports.content IS 'Full markdown content of the weekly deal report';
